apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - mappingMethod: claim
      name: SikaLabs_SSO
      type: OpenID
      openID:
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - email
        clientID: okd-training
        clientSecret:
          name: openid-client-secret-sikalabs-sso
        extraScopes: []
        issuer: 'https://sso.sikalabs.com/realms/sikalabs'
---
apiVersion: v1
kind: Secret
metadata:
  name: openid-client-secret-sikalabs-sso
  namespace: openshift-config
type: Opaque
stringData:
  clientSecret: okd-training
